### ISSUE TITLE
[FEATURE] Add support for Typescript

### ISSUE THREAD

**Issue by kraulain** [BuildForSDG/Team-222-SDG2-P1#6]
# Background
Plain Javascript can be harder to collaborate in and can make project management a little harder because it lacks many features. Typescript is a superset of javascript that enables us to write object-oriented code that compiles to javascript and that is fully interoperable with javascript. 
# Requirements
Add support for Typescript to the project
# Tasks
- [ ] Add Typescript dependencies to `package.json`
- [ ] Add Typescript-jest dependencies for testing
- [ ] Update Readme file to reflect new instructions for running and testing
